apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: alpine-cpu-hpa
  namespace: ic-ws-018
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
